from __future__ import annotations
from pathlib import Path
#!/usr/bin/env python3
"""rich_summary.py

Entry point for building a "rich" post-game summary from an existing
film-processing pipeline.

Usage
-----
```
python rich_summary.py --video VIDEO.mp4 --out OUT_DIR [options]
```

The script expects the ``OUT_DIR`` to contain JSONL artefacts generated by the
earlier pipeline (``plays.jsonl``, ``tracking.jsonl`` etc.).  It validates the
play windows against the supplied video, computes basic metrics and produces a
coach-facing markdown/PDF report together with highlight reels.  Only a subset
of the full specification is implemented here but the structure is designed to
be robust and easily extensible.

Common issues
-------------
* **FFmpeg missing** – ensure ``ffmpeg`` is available on ``$PATH``.
* **Invalid JSONL** – each line in ``*.jsonl`` files must be valid JSON.
* **No valid plays** – if play start/end times are missing or fall outside the
  video duration the script will exit with a non‑zero status.

This module is intentionally self‑contained so it can be copied into other
projects if desired.
"""


import argparse
import shutil
import subprocess

import csv
import json
import logging
import math
def detect_encoder():
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        return "libx264"
    try:
        out = subprocess.run([ffmpeg, "-hide_banner", "-encoders"],
                             capture_output=True, text=True, timeout=5)
        if out.returncode == 0 and "h264_v4l2m2m" in out.stdout:
            return "h264_v4l2m2m"
    except Exception:
        pass
    return "libx264"

ENCODER_OPTS = {
    "h264_v4l2m2m": ["-c:v","h264_v4l2m2m","-b:v","4M","-pix_fmt","yuv420p"],
    "libx264":      ["--ENCODER--","-preset","veryfast","-crf","23","-pix_fmt","yuv420p"],
}

from typing import Any, Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
import yaml
import cv2
try:  # optional PDF dependency
    from fpdf import FPDF
except Exception:  # pragma: no cover - missing dependency handled at runtime
    FPDF = None  # type: ignore
import re

# --- stable ffmpeg runner (auto-inserted) ---
def _detect_encoder():
    import shutil, subprocess
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        return "libx264"
    try:
        out = subprocess.run([ffmpeg, "-hide_banner", "-encoders"],
                             capture_output=True, text=True, timeout=5)
        if out.returncode == 0 and "h264_v4l2m2m" in out.stdout:
            return "h264_v4l2m2m"
    except Exception:
        pass
    return "libx264"

_ENCODER_OPTS = {
    "h264_v4l2m2m": ["-c:v","h264_v4l2m2m","-b:v","4M","-pix_fmt","yuv420p"],
    "libx264":      ["-c:v","libx264","-preset","veryfast","-crf","23","-pix_fmt","yuv420p"],
}
_AUDIO_OPTS = ["-c:a","aac","-b:a","128k","-ar","48000","-ac","2"]

def _ensure_codec_flags(cmd:list, enc:str)->list:
    cmd = cmd[:]
    has_cv = any(x == "-c:v" for x in cmd)
    has_ca = any(x == "-c:a" for x in cmd)
    ins = len(cmd)-1 if len(cmd)>=2 else len(cmd)  # before output
    if not has_cv:
        cmd[ins:ins] = _ENCODER_OPTS.get(enc, _ENCODER_OPTS["libx264"]); ins = len(cmd)-1
    if not has_ca:
        cmd[ins:ins] = _AUDIO_OPTS; ins = len(cmd)-1
    if "-shortest" not in cmd:
        cmd.insert(ins, "-shortest")
    return cmd

def _run_ffmpeg_command(cmd:list, timeout:int=180):
    import subprocess
    enc = _detect_encoder()
    cmd = _ensure_codec_flags(cmd, enc)
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return proc.returncode == 0, proc.stdout, proc.stderr
    except subprocess.TimeoutExpired as e:
        return False, "", f"ffmpeg timeout after {timeout}s: {e}"
    except Exception as e:
        return False, "", f"ffmpeg error: {e}"
# --- end stable runner ---



log = logging.getLogger(__name__)

def _soften_tokens(text, max_run=80):
    # Insert a zero-width space after every max_run non-space chars
    pat = re.compile(r'\S{' + str(max_run) + r'}')
    return pat.sub(lambda m: m.group(0) + '\u200b', text)
def read_jsonl(path: Path) -> List[Dict[str, Any]]:
    """Read a ``.jsonl`` file and return a list of dictionaries."""

    items: List[Dict[str, Any]] = []
    if not path.exists():
        logging.warning("%s missing", path)
        return items
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                items.append(json.loads(line))
            except json.JSONDecodeError as exc:
                logging.debug("Skipping bad JSON line in %s: %s", path, exc)
    logging.debug("Loaded %d rows from %s", len(items), path)
    return items


def find_field(d: Dict[str, Any], names: Iterable[str]) -> Any:
    """Return the value for the first key in ``names`` present in ``d``.

    The check is case-insensitive and will match "start_s" against keys such as
    "Start" or "START_S".
    """

    lowered = {k.lower(): k for k in d.keys()}
    for name in names:
        key = lowered.get(name.lower())
        if key is not None:
            return d[key]
    return None


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Play ingestion and processing


def ingest_plays(
    plays_data: List[Dict[str, Any]],
    pred_data: List[Dict[str, Any]],
    grades_data: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Merge play, prediction and grading information into a single list."""

    plays: List[Dict[str, Any]] = []
    for idx, raw in enumerate(plays_data):
        play: Dict[str, Any] = dict(raw)
        play_id = find_field(play, ["play_id", "id", "index"]) or idx + 1
        play["play_id"] = int(play_id)

        start = find_field(
            play,
            ["start_s", "start", "start_time", "t0", "ts", "begin", "clip_start"],
        )
        end = find_field(
            play,
            ["end_s", "end", "end_time", "t1", "te", "finish", "clip_end"],
        )
        try:
            play["start_s"] = float(start)
            play["end_s"] = float(end)
        except Exception:
            play["start_s"] = math.nan
            play["end_s"] = math.nan
        plays.append(play)

    # merge prediction labels
    for idx, pred in enumerate(pred_data):
        pid = find_field(pred, ["play_id", "id"]) or idx + 1
        label = find_field(pred, ["label", "prediction", "formation"]) or "UNKNOWN"
        if 0 < int(pid) <= len(plays):
            plays[int(pid) - 1]["label"] = label

    # merge grades
    for idx, grade in enumerate(grades_data):
        pid = find_field(grade, ["play_id", "id"]) or idx + 1
        ag = find_field(grade, ["grade", "agg_grade"])
        if ag is None and isinstance(grade.get("grades"), dict):
            vals = [v for v in grade["grades"].values() if isinstance(v, (int, float))]
            ag = float(np.mean(vals)) if vals else None
        if 0 < int(pid) <= len(plays) and ag is not None:
            plays[int(pid) - 1]["agg_grade"] = float(ag)
        if 0 < int(pid) <= len(plays) and isinstance(grade.get("grades"), dict):
            plays[int(pid) - 1]["grades"] = grade["grades"]
    return plays


def get_video_info(video_path: Path) -> Tuple[float, float]:
    """Return ``(duration_seconds, fps)`` for ``video_path``."""

    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise FileNotFoundError(f"Unable to open video: {video_path}")
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    frame_count = cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0
    duration = frame_count / fps if frame_count else 0
    cap.release()
    return float(duration), float(fps)


def normalize_windows(
    plays: List[Dict[str, Any]], video_duration: float, min_len: float
) -> Tuple[List[Dict[str, Any]], Dict[str, int], Dict[int, str], str]:
    """Normalize play start/end times and filter invalid windows.

    Parameters
    ----------
    plays:
        List of play dictionaries possibly containing various start/end keys.
    video_duration:
        Duration of the source video in seconds.
    min_len:
        Minimum allowed clip length in seconds.

    Returns
    -------
    (valid_plays, exclusion_stats, per_play_reasons, unit)
        ``valid_plays`` are mutated in-place with ``start_s``/``end_s`` fields
        normalised to seconds. ``exclusion_stats`` tallies the number of dropped
        rows per reason and ``per_play_reasons`` maps the original play index to
        the exclusion reason. ``unit`` describes whether timestamps were assumed
        to be in seconds or converted from milliseconds.
    """

    start_vals: List[float] = []
    for p in plays:
        start_raw = find_field(p, ["start_s", "start", "start_time", "t0", "ts", "begin", "clip_start"])
        try:
            if start_raw is not None:
                start_vals.append(float(start_raw))
        except Exception:
            continue
    median_start = float(np.median(start_vals)) if start_vals else 0.0
    unit = "seconds"
    factor = 1.0
    if median_start > video_duration * 1.2:
        unit = "milliseconds->seconds"
        factor = 0.001

    valid: List[Dict[str, Any]] = []
    exclusion_stats: Dict[str, int] = {}
    per_play_reasons: Dict[int, str] = {}

    for idx, play in enumerate(plays):
        s_raw = find_field(play, ["start_s", "start", "start_time", "t0", "ts", "begin", "clip_start"])
        e_raw = find_field(play, ["end_s", "end", "end_time", "t1", "te", "finish", "clip_end"])
        try:
            start = float(s_raw) * factor
            end = float(e_raw) * factor
        except Exception:
            per_play_reasons[idx] = "missing_time"
            exclusion_stats["missing_time"] = exclusion_stats.get("missing_time", 0) + 1
            continue
        start = max(0.0, min(video_duration, start))
        end = max(0.0, min(video_duration, end))
        if end <= start:
            per_play_reasons[idx] = "end_before_start"
            exclusion_stats["end_before_start"] = exclusion_stats.get("end_before_start", 0) + 1
            continue
        if end - start < min_len:
            per_play_reasons[idx] = "too_short"
            exclusion_stats["too_short"] = exclusion_stats.get("too_short", 0) + 1
            continue
        play["start_s"] = float(start)
        play["end_s"] = float(end)
        play["duration"] = float(end - start)
        valid.append(play)

    return valid, exclusion_stats, per_play_reasons, unit


def validate_plays(
    plays: List[Dict[str, Any]],
    *,
    duration: float,
    min_len: float = 3.0,
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Split plays into valid and invalid lists after sanity checks."""

    valid: List[Dict[str, Any]] = []
    invalid: List[Dict[str, Any]] = []
    last_end = 0.0
    for play in sorted(plays, key=lambda p: p.get("start_s", 0)):
        start, end = play.get("start_s"), play.get("end_s")
        if start is None or end is None or math.isnan(start) or math.isnan(end):
            play["invalid_reason"] = "missing_time"
            invalid.append(play)
            continue
        start = max(0.0, float(start))
        end = min(duration, float(end))
        if end - start < min_len:
            play["invalid_reason"] = "too_short"
            invalid.append(play)
            continue
        if start < last_end:
            overlap = last_end - start
            if overlap > 0.75:
                start = last_end + 0.01
        last_end = end
        play["start_s"], play["end_s"] = start, end
        play["duration"] = end - start
        valid.append(play)
    return valid, invalid


def classify_plays(
    plays: List[Dict[str, Any]], wins_th: float, corrections_th: float
) -> None:
    for play in plays:
        grade = play.get("agg_grade")
        if grade is None:
            play["tag"] = "NEUTRAL"
        elif grade >= wins_th:
            play["tag"] = "WIN"
        elif grade <= corrections_th:
            play["tag"] = "CORRECTION"
        else:
            play["tag"] = "NEUTRAL"


# ---------------------------------------------------------------------------
# Reporting helpers


def compute_metrics(valid: List[Dict[str, Any]], invalid: List[Dict[str, Any]]) -> Dict[str, Any]:
    label_counts: Dict[str, int] = {}
    for p in valid:
        label = p.get("label", "UNKNOWN")
        label_counts[label] = label_counts.get(label, 0) + 1
    total_runtime = sum(p.get("duration", 0.0) for p in valid)
    win_count = sum(1 for p in valid if p.get("tag") == "WIN")
    corr_count = sum(1 for p in valid if p.get("tag") == "CORRECTION")
    metrics = {
        "plays_detected": len(valid) + len(invalid),
        "valid_plays_used": len(valid),
        "invalid_plays": len(invalid),
        "total_clip_runtime": total_runtime,
        "label_counts": label_counts,
        "wins": win_count,
        "corrections": corr_count,
    }
    return metrics


def write_timeline_csv(plays: List[Dict[str, Any]], path: Path) -> None:
    ensure_dir(path.parent)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "play_id",
            "t_start",
            "t_end",
            "duration",
            "label",
            "agg_grade",
            "tag",
        ])
        for p in plays:
            writer.writerow(
                [
                    p.get("play_id"),
                    f"{p.get('start_s', 0):.2f}",
                    f"{p.get('end_s', 0):.2f}",
                    f"{p.get('duration', 0):.2f}",
                    p.get("label", "UNKNOWN"),
                    p.get("agg_grade", ""),
                    p.get("tag", ""),
                ]
            )


def write_summary_json(metrics: Dict[str, Any], path: Path) -> None:
    ensure_dir(path.parent)
    with path.open("w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)


def generate_report_md(
    metadata: Dict[str, Any], metrics: Dict[str, Any], plays: List[Dict[str, Any]]
) -> str:
    lines: List[str] = []
    lines.append("# Game Report")
    lines.append("")
    lines.append(f"Team: {metadata.get('team_us', '')}")
    lines.append(f"Opponent: {metadata.get('opponent', '')}")
    lines.append(f"Date: {metadata.get('date', '')}")
    lines.append("")
    lines.append("## Summary")
    lines.append(
        f"Plays detected: {metrics['plays_detected']} (valid {metrics['valid_plays_used']})"
    )
    lines.append(
        f"Total clip runtime: {metrics['total_clip_runtime']:.1f} seconds"
    )
    if metrics["label_counts"]:
        lines.append("Label mix:")
        for label, cnt in metrics["label_counts"].items():
            lines.append(f"- {label}: {cnt}")
    lines.append("")

    wins = [p for p in plays if p.get("tag") == "WIN"]
    corrs = [p for p in plays if p.get("tag") == "CORRECTION"]
    lines.append("## Top Wins")
    for p in sorted(wins, key=lambda x: x.get("agg_grade", 0), reverse=True)[:5]:
        lines.append(
            f"- Play {p['play_id']} ({p.get('label', 'UNKNOWN')}) grade={p.get('agg_grade', 0):.2f}"
        )
    lines.append("")
    lines.append("## Top Corrections")
    for p in sorted(corrs, key=lambda x: x.get("agg_grade", 0))[:5]:
        lines.append(
            f"- Play {p['play_id']} ({p.get('label', 'UNKNOWN')}) grade={p.get('agg_grade', 0):.2f}"
        )

    lines.append("")
    lines.append("## Full Play Table")
    lines.append("play_id | start | end | label | grade | tag")
    lines.append("---|---|---|---|---|---")
    for p in plays:
        lines.append(
            f"{p['play_id']} | {p.get('start_s', 0):.2f} | {p.get('end_s', 0):.2f} | "
            f"{p.get('label', 'UNKNOWN')} | {p.get('agg_grade', '')} | {p.get('tag', '')}"
        )

    lines.append("")
    lines.append("## Data provenance")
    lines.append("Report generated by rich_summary.py")
    return "\n".join(lines)

def write_md(md_text: str, md_path: Path) -> None:
    """Write markdown text to ``md_path``."""
    ensure_dir(md_path.parent)
    md_path.write_text(md_text, encoding="utf-8")


def render_pdf_fpdf(md_path: Path, pdf_path: Path) -> None:
    """Render ``md_path`` into ``pdf_path`` using FPDF."""
    if FPDF is None:  # dependency missing
        raise RuntimeError("FPDF library not available")
    txt = md_path.read_text(encoding="utf-8", errors="replace")
    ensure_dir(pdf_path.parent)
    pdf = FPDF()
    pdf.set_auto_page_break(True, 15)
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.set_left_margin(12)
    pdf.set_right_margin(12)
    pdf.set_font("Helvetica", size=12)
    for line in txt.splitlines():
        pdf.multi_cell(0, 8, _soften_tokens(line))
    pdf.output(str(pdf_path))
    log.info("FPDF PDF written: %s", pdf_path)


def render_pdf_reportlab(md_path: Path, pdf_path: Path) -> None:
    """Render ``md_path`` into ``pdf_path`` using ReportLab."""
    try:
        from reportlab.platypus import Preformatted, SimpleDocTemplate
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
    except Exception as exc:  # pragma: no cover - dependency issues
        log.warning("ReportLab not available: %s", exc)
        return

    txt = md_path.read_text(encoding="utf-8", errors="replace")
    ensure_dir(pdf_path.parent)
    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )
    style = getSampleStyleSheet()["Code"]
    doc.build([Preformatted(txt, style)])
    log.info("ReportLab PDF written: %s", pdf_path)


def generate_snapshots(video_path: Path, plays: List[Dict[str, Any]], out_path: Path) -> None:
    ensure_dir(out_path.parent)
    cap = cv2.VideoCapture(str(video_path))
    thumbs: List[np.ndarray] = []
    for play in plays:
        cap.set(cv2.CAP_PROP_POS_MSEC, play["start_s"] * 1000)
        ok, frame = cap.read()
        if not ok:
            continue
        cv2.putText(
            frame,
            f"#{play['play_id']}",
            (10, 40),
            cv2.FONT_HERSHEY_SIMPLEX,
            1.0,
            (0, 255, 0),
            2,
            cv2.LINE_AA,
        )
        thumbs.append(frame)
    cap.release()
    if not thumbs:
        return
    cols = int(math.ceil(math.sqrt(len(thumbs))))
    rows = int(math.ceil(len(thumbs) / cols))
    h, w, _ = thumbs[0].shape
    grid = np.zeros((rows * h, cols * w, 3), dtype=thumbs[0].dtype)
    for idx, img in enumerate(thumbs):
        r = idx // cols
        c = idx % cols
        grid[r * h : (r + 1) * h, c * w : (c + 1) * w] = img
    cv2.imwrite(str(out_path), grid)


# ---------------------------------------------------------------------------
# FFmpeg based clipping


def cut_clip(
    video: Path,
    start: float,
    end: float,
    text: str,
    out_path: Path,
    encoder: str,
) -> bool:
    draw = (
        "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
        f"text='{text}':x=10:y=h-40:fontsize=24:fontcolor=white:box=1:boxcolor=0x00000099"
    )
    cmd = [
        "ffmpeg",
        "-y",
        "-ss",
        f"{start:.2f}",
        "-to",
        f"{end:.2f}",
        "-i",
        str(video),
        "-vf",
        draw,
        "-c:v",
        encoder,
        "-c:a",
        "copy",
        str(out_path),
    ]
    ret, _, _ = _run_ffmpeg_command(cmd, timeout=120)
    return ret == 0


def concat_clips(clips: List[Path], out_path: Path, encoder: str) -> bool:
    if not clips:
        return False
    ensure_dir(out_path.parent)
    list_file = out_path.parent / "concat_list.txt"
    with list_file.open("w", encoding="utf-8") as f:
        for clip in clips:
            f.write(f"file '{clip}'\n")
    cmd = [
        "ffmpeg",
        "-y",
        "-f",
        "concat",
        "-safe",
        "0",
        "-i",
        str(list_file),
        "-c",
        "copy",
        str(out_path),
    ]
    ret, _, _ = _run_ffmpeg_command(cmd, timeout=120)
    list_file.unlink(missing_ok=True)
    return ret == 0


# ---------------------------------------------------------------------------
# HUDL CSV


def hudl_time(sec: float) -> str:
    m = int(sec // 60)
    s = sec - m * 60
    return f"{m:02d}:{s:06.3f}"


def export_hudl_csv(plays: List[Dict[str, Any]], path: Path) -> None:
    ensure_dir(path.parent)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Label", "Start Time", "End Time", "Duration", "Notes", "Playlist"])
        for p in plays:
            playlist = (
                "Wins" if p.get("tag") == "WIN" else "Corrections" if p.get("tag") == "CORRECTION" else "Highlights"
            )
            writer.writerow(
                [
                    p.get("label", "UNKNOWN"),
                    hudl_time(p["start_s"]),
                    hudl_time(p["end_s"]),
                    f"{p['duration']:.2f}",
                    "",
                    playlist,
                ]
            )


# ---------------------------------------------------------------------------
# Main entrypoint


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Build rich film summaries")

    def clip_length(value: str) -> float:
        v = float(value)
        if v < 0.5:
            raise argparse.ArgumentTypeError("min-clip-sec must be >= 0.5")
        return v

    parser.add_argument("--video", required=True, help="MP4 path")
    parser.add_argument("--out", required=True, help="Pipeline output folder")
    parser.add_argument("--team")
    parser.add_argument("--opponent")
    parser.add_argument("--date")
    parser.add_argument("--wins-threshold", type=float, default=3.0)
    parser.add_argument("--corrections-threshold", type=float, default=2.0)
    parser.add_argument("--export-hudl", action="store_true")
    parser.add_argument("--per-player-cutups", action="store_true")
    parser.add_argument("--max-top", type=int, default=10)
    parser.add_argument("--min-clip-sec", type=clip_length, default=2.0)
    parser.add_argument("--dry-run", action="store_true", help="Skip clip rendering")
    parser.add_argument(
        "--pdf-engine",
        choices=["fpdf", "reportlab", "none"],
        default="reportlab",
        help="PDF rendering backend",
    )
    args = parser.parse_args(argv)

    video_path = Path(args.video)
    out_dir = Path(args.out)

    if not video_path.exists():
        print("Video not found", video_path)
        return 1

    # logging setup
    log_path = out_dir / "logs" / "rich_summary.log"
    ensure_dir(log_path.parent)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=[logging.FileHandler(log_path), logging.StreamHandler()],
    )

    duration, fps = get_video_info(video_path)
    logging.info("Video duration %.2fs @ %.2ffps", duration, fps)

    # metadata
    metadata_path = out_dir / "metadata.json"
    metadata: Dict[str, Any] = {}
    if metadata_path.exists():
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    if args.team:
        metadata["team_us"] = args.team
    if args.opponent:
        metadata["opponent"] = args.opponent
    if args.date:
        metadata["date"] = args.date
    metadata["video_path"] = str(video_path)
    ensure_dir(metadata_path.parent)
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    # ingest jsonls
    plays_data = read_jsonl(out_dir / "plays.jsonl")
    pred_data = read_jsonl(out_dir / "play_predictions.jsonl")
    grades_data = read_jsonl(out_dir / "grades.jsonl")
    plays = ingest_plays(plays_data, pred_data, grades_data)

    norm_plays, excl_stats, per_play_reasons, unit = normalize_windows(
        plays, duration, args.min_clip_sec
    )
    valid, invalid_post = validate_plays(
        norm_plays, duration=duration, min_len=args.min_clip_sec
    )

    invalid_norm = []
    for idx, reason in per_play_reasons.items():
        raw = dict(plays[idx])
        raw["invalid_reason"] = reason
        invalid_norm.append(raw)
    invalid = invalid_norm + invalid_post

    classify_plays(valid, args.wins_threshold, args.corrections_threshold)

    metrics = compute_metrics(valid, invalid)
    write_timeline_csv(valid, out_dir / "dashboards" / "timeline.csv")
    write_summary_json(metrics, out_dir / "dashboards" / "summary.json")

    report = {
        "video_duration": float(duration),
        "min_clip_sec": float(args.min_clip_sec),
        "unit": unit,
        "total_rows": len(plays),
        "valid_rows": len(valid),
        "exclusions": excl_stats,
        "examples": [
            {"idx": int(i), "reason": r, "raw": plays[int(i)]}
            for i, r in list(per_play_reasons.items())[:10]
        ],
    }
    report_path = out_dir / "sanity" / "validation_report.json"
    ensure_dir(report_path.parent)
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    logging.info(
        "Validation: %d/%d rows valid (unit=%s); exclusions=%s",
        len(valid),
        len(plays),
        unit,
        excl_stats,
    )

    md_text = generate_report_md(metadata, metrics, valid)
    md_path = out_dir / "reports" / "report.md"
    pdf_path = out_dir / "reports" / "report.pdf"
    write_md(md_text, md_path)

    generate_snapshots(
        video_path, valid, out_dir / "sanity" / "snapshots.jpg"
    )

    encoder = detect_encoder()

    # highlight clips -----------------------------------------------------
    if not args.dry_run:
        tmp_dir = out_dir / "clips" / "tmp"
        ensure_dir(tmp_dir)

        def build_clip_list(sel: List[Dict[str, Any]]) -> List[Path]:
            out_paths: List[Path] = []
            for p in sel:
                text = f"#{p['play_id']} | {p.get('label', 'UNKNOWN')} | grade:{p.get('agg_grade',0):.2f} | {p.get('tag')}"
                tmp = tmp_dir / f"clip_{p['play_id']}.mp4"
                ok = cut_clip(
                    video_path, p["start_s"], p["end_s"], text, tmp, encoder
                )
                if not ok:
                    logging.error("Failed to render clip %s", tmp)
                    return []
                out_paths.append(tmp)
            return out_paths

        # team highlights: top plays by grade but max 2 per label
        top_sorted = sorted(valid, key=lambda x: x.get("agg_grade", 0), reverse=True)
        label_counter: Dict[str, int] = {}
        highlights: List[Dict[str, Any]] = []
        for p in top_sorted:
            label = p.get("label", "UNKNOWN")
            if label_counter.get(label, 0) >= 2:
                continue
            label_counter[label] = label_counter.get(label, 0) + 1
            highlights.append(p)
            if len(highlights) >= args.max_top:
                break
        highlight_clips = build_clip_list(highlights)
        concat_clips(
            highlight_clips,
            out_dir / "clips" / "highlights" / "team_highlights.mp4",
            encoder,
        )

        wins = [p for p in valid if p.get("tag") == "WIN"]
        wins = sorted(wins, key=lambda x: x.get("agg_grade", 0), reverse=True)[
            : args.max_top
        ]
        win_clips = build_clip_list(wins)
        concat_clips(
            win_clips,
            out_dir / "clips" / "wins" / "top_wins.mp4",
            encoder,
        )

        corr = [p for p in valid if p.get("tag") == "CORRECTION"]
        corr = sorted(corr, key=lambda x: x.get("agg_grade", 0))[: args.max_top]
        corr_clips = build_clip_list(corr)
        concat_clips(
            corr_clips,
            out_dir / "clips" / "corrections" / "top_corrections.mp4",
            encoder,
        )

        # per-player cutups ------------------------------------------------
        if args.per_player_cutups:
            vis_map_path = out_dir / "config" / "player_visual_ids.yaml"
            jersey_map: Dict[str, Any] = {}
            if vis_map_path.exists():
                jersey_map = yaml.safe_load(vis_map_path.read_text()) or {}
            for jersey in sorted(jersey_map.keys()):
                player_plays = [
                    p
                    for p in valid
                    if jersey in (p.get("players") or [])
                    or jersey in (p.get("player_ids") or [])
                ]
                if not player_plays:
                    continue
                clips = build_clip_list(player_plays)
                concat_clips(
                    clips,
                    out_dir
                    / "clips"
                    / "players"
                    / jersey
                    / f"{jersey}_cutups.mp4",
                    encoder,
                )

    # HUDL export --------------------------------------------------------
    if args.export_hudl:
        export_hudl_csv(
            valid,
            out_dir / "hudl_export" / "hudl_export.csv",
        )

    # PDF rendering ------------------------------------------------------
    if args.pdf_engine == "reportlab":
        render_pdf_reportlab(md_path, pdf_path)
    elif args.pdf_engine == "fpdf":
        try:
            render_pdf_fpdf(md_path, pdf_path)
        except Exception as exc:
            log.warning("FPDF failed (%s); falling back to ReportLab", exc)
            render_pdf_reportlab(md_path, pdf_path)
    else:
        log.info("PDF rendering skipped")

    # Final output -------------------------------------------------------
    print("Summary written to", out_dir)
    print("Valid plays:", metrics["valid_plays_used"])
    if pdf_path.exists():
        print("Report:", pdf_path)
    else:
        print("Report: PDF not generated")
    if metrics["valid_plays_used"] < 5:
        print(
            "ACTIONABLE HINTS: very few valid plays detected; check validation_report.json and consider lowering --min-clip-sec"
        )

    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())



def _encoder_flags(enc):
    return ENCODER_OPTS.get(enc or "libx264", ENCODER_OPTS["libx264"])

def _splice_encoder(cmd:list, enc:str)->list:
    if "--ENCODER--" in cmd:
        ix = cmd.index("--ENCODER--")
        return cmd[:ix] + _encoder_flags(enc) + cmd[ix+1:]
    return cmd

def _ensure_codec_flags(cmd:list, encoder:str)->list:
    cmd = cmd[:]
    has_cv = any(x == "-c:v" for x in cmd)
    has_ca = any(x == "-c:a" for x in cmd)
    # Insert before the final output path (last token)
    insert_at = len(cmd)-1 if len(cmd)>=2 else len(cmd)
    if not has_cv:
        cmd[insert_at:insert_at] = ENCODER_OPTS.get(encoder, ENCODER_OPTS["libx264"])
        insert_at = len(cmd)-1
    if not has_ca:
        cmd[insert_at:insert_at] = AUDIO_OPTS
        insert_at = len(cmd)-1
    # Shortest avoids audio/video length mismatch hangs
    if "-shortest" not in cmd:
        cmd.insert(insert_at, "-shortest")
    return cmd

def _run_ffmpeg_command(cmd:list, timeout:int=120):
    enc = detect_encoder()
    cmd = _ensure_codec_flags(cmd, enc)
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        ok = (proc.returncode == 0)
        return ok, proc.stdout, proc.stderr
    except subprocess.TimeoutExpired as e:
        return False, "", f"ffmpeg timeout after {timeout}s: {e}"
    except Exception as e:
        return False, "", f"ffmpeg error: {e}"
